---
format:
  html:
    embed-resources: true
---

# [GUI, tuantuan, PhD]{style="color: navy"}

#### 

+--------------------------------------------------------------------------------------------------------+-------------------------------------------------:+
| ## [Contact Information]{style="color: #990000"}                                                       
| 
| -   School of Life Sciences and Biotechnology, Shanghai Jiao Tong University, Shanghai 200030, China   
|
| -   guituantuan\@sjtu.edu.cn                                                                           
|                                                                                                        
| -   guituant2009\@163.com                                   
|
|     Last updated on Dec-13-2024.                                                                       
+--------------------------------------------------------------------------------------------------------+--------------------------------------------------+

## [Education]{style="color: #990000"}

#### - Shanghai Jiao Tong University, Shanghai, China (2020 - 2024)

-   **Ph.D candidate in Bioinformatics.**  School of Life Sciences and Biotechnology, supervised by Saijuan Chen, Zhu Chen & Hai Fang

#### - University of Chinese Academy of Sciences, Shanghai, China (2013 - 2016)

-   **Master in Bioinformatics.** Shanghai Institutes of Biological of Science, supervised by Yixue Li & Lei Liu

#### - Zhengzhou University, Zhengzhou, China (2009 - 2013)

-   **Bachelor in Bioengineering.**

## [Selected Publications]{style="color: #990000"}

**PhD period:**

1.  **Tuantuan Gui**, *et al.* **MNet: a metabolic network-centered tool for interpreting metabolomic and
transcriptomic data** (*Journal of Molecular Biology*, Under Review, First author)

2. Junyu Wang#, **Tuantuan Gui**#, *et al.* **Metabolomic insights into pathogenesis and therapeutic potential in
adult acute lymphoblastic leukemia** (*PNAS*, Revised, Co-first author)

**Master period:**

3. **Tuantuan Gui**, *et al.* **Identification of hepatocellular carcinoma-related genes with a machine learning and network analysis**, 2015, *J Comput Biol*

4. Zhi Liu, **Tuantuan Gui**, *et al.* **cisASE: a likelihood-based method for detecting putative cis-regulated allele-specific expression in RNA sequencing data**, 2016, *Bioinformatics*

**Others:**

5. Min Emma Huang, Yining Qin, Yafang Shang, Qian Hao, Chuanzong Zhan, Chaoyang Lian, Simin Luo, Liu Daisy Liu, Senxin Zhang, Yu Zhang, Yang Wo, Niu Li, Shuheng Wu, **Tuantuan Gui**, Binbin Wang, Yifeng Luo, Yanni Cai, Xiaojing Liu, Ziye Xu, Pengfei Dai, Simiao Li, Liang Zhang, Junchao Dong, Jian Wang, Xiaoqi Zheng, Yingjie Xu, Yihua Sun, Wei Wu, Leng-Siew Yeap, Fei-Long Meng. **C-to-G editing generates double-strand breaks causing deletion, transversion and translocation**, 2024, *Nat Cell Biol*

6. Yanyan Wang, Senxin Zhang, Xinrui Yang, Joyce K Hwang, Chuanzong Zhan, Chaoyang Lian, Chong Wang, **Tuantuan Gui**, Binbin Wang, Xia Xie, Pengfei Dai, Lu Zhang, Ying Tian, Huizhi Zhang, Chong Han, Yanni Cai, Qian Hao, Xiaofei Ye, Xiaojing Liu, Jiaquan Liu, Zhiwei Cao, Shaohui Huang, Jie Song, Qiang Pan-Hammarström, Yaofeng Zhao, Frederick W Alt, Xiaoqi Zheng, Lin-Tai Da, Leng-Siew Yeap, Fei-Long Meng. **Mesoscale DNA feature in antibody-coding sequence facilitates somatic hypermutation**, 2023, *Cell*

7. Qian Hao, Chuanzong Zhan, Chaoyang Lian, Simin Luo, Wenyi Cao, Binbin Wang, Xia Xie, Xiaofei Ye, **Tuantuan Gui**, Claudia Voena, Chiara Pighi, Yanyan Wang, Ying Tian, Xin Wang, Pengfei Dai, Yanni Cai, Xiaojing Liu, Shengqun Ouyang, Shiqi Sun, Qianwen Hu, Jun Liu, Youqiong Ye, Jingkun Zhao, Aiguo Lu, Ji-Yang Wang, Chuanxin Huang, Bing Su, Fei-Long Meng, Roberto Chiarle, Qiang Pan-Hammarström, Leng-Siew Yeap. **DNA repair mechanisms that promote insertion-deletion events during immunoglobulin gene diversification**, 2023, *Sci Immunol*

8. Dingpeng Yang, Ying Sun, Jingjing Chen, Ying Zhang, Shuangshuang Fan, Min Huang, Xia Xie, Yanni Cai, Yafang Shang, **Tuantuan Gui**, Liming Sun, Jiazhi Hu, Junchao Dong, Leng-Siew Yeap, Xiaoming Wang, Wei Xiao, Fei-Long Meng. **REV7 is required for processing AID initiated DNA lesions in activated B cells**, 2020, *Nat Commun*

## [Research Experience]{style="color: #990000"}

**Creation of R package MNet and website**

**Code:** https://github.com/tuantuangui/MNet    
**Website:** http://www.mnet4all.com/MNet/

1. MNet incorporates ‘dbMNet’, an expert-curated knowledgebase serving as a unique reference resource for
metabolomics, which includes all currently available gene-metabolite and metabolite-metabolite pairs in
humans, alongside ‘dbKEGG’, a pathway knowledgebase based on KEGG
2. MNet implements extended pathway enrichment analysis, extended differential abundance analysis, and
extended data set enrichment analysis, enabling the identification of dysregulated metabolic pathways by
simultaneously considering both metabolites and genes
3. Leveraging the dbMNet knowledgebase, MNet facilitates metabolic-related network analysis, considering
both metabolite-metabolite and gene-metabolite interactions, offering a thorough understanding of
metabolic interconnections

**Analysis of the metabolism and RNA-seq data from acute lymphoblastic leukemia patients**  

**Code:** http://www.genetictargets.com/MALL2BOOKLET/index.html  

1. The intracellular and serum metabolomic profile was constructed based on the MNet  
2. Enabling the development of a clustering system to supplement existing risk stratification based on the
comprehensive metabolic information dataset

## [Research Skills]{style="color: #990000"}
Programming: R, Perl, Python  
Visualization: R Shiny

## [Honors and Award]{style="color: #990000"}
2016 Excellent Graduates in Shanghai  
2015 National Scholarship


